### PR TITLE
docs: Add ITP's TransitExplorer tool to visualization category

### PR DESCRIPTION
**Pull request by markjd84**
We haven't even sorted a domain name yet, but there is an article explaining TransitExplorer and I'll put a gif below. If anyone wants to try it, or more info, give me a shout :)

...oop the GIF is too big for GH, but you can see it on [twitter](https://twitter.com/ITPtweet/status/1470700028654235651)

Thanks!

### CODE REVIEW

**Comment by barbeau** [comment]
@markjd84 Thanks for sharing this! Could you clarify if this tool is free to use?

**Comment by markjd84** [comment]
It's not, sorry, though we haven't got fixed pricing in place yet. Anyone who wants to try it is welcome to drop me a line! 

edit: contact, if useful: dimond@itpworld.net or through GH

**Comment by barbeau** [comment]
@markjd84 Ok - I'm going to hold off merging this for now until you've got a permanent webpage and pricing is determined. Most of the resources on this list are free and open-source, so I just want to make sure that those that aren't are appropriately labeled to avoid confusion. This might entail a new section in the list (similar to "Native Apps (closed source)").

**Comment by barbeau** [comment]
One option would be to add another community-maintained list:
https://github.com/CUTR-at-USF/awesome-transit#community-maintained-lists

...that's "Entities providing GTFS analysis services" or something similar, and capture commercial services like yours there.

**Comment by markjd84** [comment]
Ok, no problem, thanks for info!

**Comment by Mbarnes2022** [comment]
I had my covered vaccine Johnson & Johnson however I lost my card I had it in Columbus Ohio at the hilltop Westgate Park at the recreational center back in March to July of 2021 how do I find my proof

**Review by carlfredl — DISMISSED** [review]

**Comment by carlfredl** [comment]
@markjd84 are there any updates on this project you can share?

**Pull request closed without merging**
