### PR TITLE
docs: change of organization from CanalTP to hove-io

### PR DESCRIPTION
**Pull request by woshilapin**
The `CanalTP` organization recently changed its name to `hove-io`. Github already does automatic redirection but changing to the new name is probably better.

### CODE REVIEW

**Comment by woshilapin** [comment]
This Contributor License Agreement is a bit annoying. I understand the need... but with my email it should be enough. Why the need of my mailing address and my phone number? I'm not really ok to share all of these relatively private information.

**Comment by barbeau** [comment]
@woshilapin That's fine if you just want to provide your email.

**Comment by woshilapin** [comment]
> @woshilapin That's fine if you just want to provide your email.

Thank you for the quick response. I thought it was not ok, since the fields are mandatory. However, no validation is done on them, so I put `NA` in them, and it worked. Thanks again.

**Review by barbeau — APPROVED** [review]
Thanks @woshilapin!

**Pull request merged**
