### PR TITLE
Add Transit Techies NYC to Community

### PR DESCRIPTION
**Pull request by tyleragreen**
Add Transit Techies NYC to Community

### CODE REVIEW

**Comment by tyleragreen** [comment]
@barbeau, just double checking: the CLA covers only the contributions to this repo, not any linked content, correct?

**Comment by tyleragreen** [comment]
Also happy to move this to `Resources` if we feel that's more appropriate.

**Comment by barbeau** [comment]
@tyleragreen Thanks!  Yes, CLA is only for the text contributed in this PR, and not any linked content.  I think Community is fine for this, although if more local community items get added we may need to re-think the organization.

**Comment by tyleragreen** [comment]
@barbeau great - thanks!

**Pull request merged**
