### PR TITLE
Adding Bongo

### PR DESCRIPTION
**Pull request by markahrens**
Real-time transit data for Iowa City, Coralville & The University of Iowa

### CODE REVIEW

**Comment by luqmaan** [comment]
Please choose one section to list Bongo in.

Is Bongo open source?

**Comment by markahrens** [comment]
Bongo is an app that we built to merge 3 transit agencies data into a single presentation. All 3 agencies use Nextbus as their provider and our app takes the data and presents it all together.

**Comment by luqmaan** [comment]
My questions is about the presentation layer. Is that part open source?

It's pretty cool that you're bringing 3 disparate data sources together into one UI. You should explain that in the description.

**Comment by markahrens** [comment]
Right now, the presentation layer is not open source. It is an interesting dynamic between the University IT, where I am at, and the transit agencies.

For explaining it in the description, did you mean on our web site or in the description on the README file?

**Comment by barbeau** [comment]
> It is an interesting dynamic between the University IT, where I am at, and the transit agencies.

@markahrens Can you elaborate on this, and why it's not open-source?  Just curious - I'm at a university as well and we've had some tension here over open-source projects.  If you'd prefer not to discuss publicly feel free to ping me on [Linked In](https://www.linkedin.com/in/seanbarbeau).

**Comment by luqmaan** [comment]
> For explaining it in the description, did you mean on our web site or in the description on the README file?

The README please.

**Comment by luqmaan** [comment]
Merging for now. Feel free to update the description to explain why bongo is awesome. :bus:

**Comment by markahrens** [comment]
@barbeau the biggest reason we have not open sourced it so far is first, we have not been asked by anyone to open source it and second, there have been discussions about possibly offering a service of hosting the software for other transit organizations. I would be more than welcome to chat more about this through email if you like too, just drop me a line.

**Comment by barbeau** [comment]
@markahrens Consider this an official request to open-source it ;).  I'll ping you via email as well.

**Pull request merged**
