### PR TITLE
add data package specification validation tool

### PR DESCRIPTION
**Pull request by antrim**
add data package specification validation tool

### CODE REVIEW

**Comment by luqmaan** [comment]
Thanks!

What do you think of this description?

```
[GFTS Data Package Specification](https://github.com/Stephen-Gates/GTFS) - A [Data Package specification](http://specs.frictionlessdata.io/data-packages/) with validation accomplished with [Good Tables](http://goodtables.okfnlabs.org/). Includes a data package, schemas, tests, and uses South East Queensland GTFS data as an example.
```

**Comment by antrim** [comment]
Great description.

What do you think about moving some of this inventory activity to TransitWiki?

I started a category here: http://www.transitwiki.org/TransitWiki/index.php?title=Category:GTFS-consuming_applications http://www.transitwiki.org/TransitWiki/index.php?title=Category:GTFS-consuming_applications

GTFS page: http://www.transitwiki.org/TransitWiki/index.php?title=General_Transit_Feed_Specification http://www.transitwiki.org/TransitWiki/index.php?title=General_Transit_Feed_Specification

**Comment by luqmaan** [comment]
Thats up to @barbeau

**Comment by barbeau** [comment]
@antrim that's a good question,  I've been debating it myself. Seems like developers are more likely to stumble on Github,  while Transit wiki is turning into a great resource.  Maintain two lists is obviously more work.

**Comment by barbeau** [comment]
To revisit moving to Transit Wiiki - one thing I think Github is good at is facilitating conversations surrounding organization of ideas.  For example, if someone wants to add something in a new section to the list, on Github they can open an issue or we can comment on pull requests.  You don't get that on TransitWiki - one person makes the edit, and for the most part no one else knows until you stumble on it later, without a simple way to publicly discuss those edits.  

So I think keeping this repo is a good idea - it helps build a community.  This repo should continue to be a simple list, though, with TransitWiki holding more extensive content.  My two cents.

**Pull request merged**
