### PR TITLE
Update OBA native app links

### PR DESCRIPTION
**Pull request by barbeau**

### CODE REVIEW

**Comment by luqmaan** [comment]
Can we make this more concise? 

Maybe something like this instead?

> - OneBusAway Apps - [Android](https://play.google.com/store/apps/details?id=com.joulespersecond.seattlebusbot) [_(source code)_](https://github.com/OneBusAway/onebusaway-android), [Fire Phone](http://www.amazon.com/gp/mas/dl/android?p=com.joulespersecond.seattlebusbot) [_(source code)_](https://github.com/OneBusAway/onebusaway-android), [iOS](https://itunes.apple.com/us/app/onebusaway/id329380089)  [_(source code)_](https://github.com/OneBusAway/onebusaway-iphone), [Windows Phone](https://www.microsoft.com/en-us/store/apps/onebusaway/9nblggh0cbd9) [_(source code)_](https://github.com/OneBusAway/onebusaway-windows-phone), [Windows 8](https://www.microsoft.com/en-us/store/apps/onebusaway/9wzdncrdm5pc) [_(source code)_](https://github.com/OneBusAway/onebusaway-windows8), [Google Glass GDK](https://github.com/OneBusAway/onebusaway-android/pull/219) [_(source code)_](https://github.com/OneBusAway/onebusaway-android/pull/219)

**Comment by barbeau** [comment]
Sure, that looks better!  I'll do this.

**Comment by barbeau** [comment]
@luqmaan Ok, just pushed that commit into this PR - it should now match your text above.

**Comment by luqmaan** [comment]
:bus:

**Pull request merged**
