### PR TITLE
Update entry about chouette

### PR DESCRIPTION
**Pull request by 1Maxnet1**
The website seems to be no longer available

### CODE REVIEW

**Comment by nestorlora** [comment]
Seems like Chouette has been slowly evolving into a SaaS agency tool to manage multi-formats schedule data.
I found [their new website](https://enroute.mobi/chouette/).
Enroute also developed a complementary tool called [Ara](https://enroute.mobi/ara/) for realtime data.

**Comment by 1Maxnet1** [comment]
> Seems like Chouette has been slowly evolving into a SaaS agency tool to manage multi-formats schedule data. I found [their new website](https://enroute.mobi/chouette/). Enroute also developed a complementary tool called [Ara](https://enroute.mobi/ara/) for realtime data.

Yes but I don't think listing the SaaS here makes any sense. But keeping the old tool for reference does imho.

**Comment by nestorlora** [comment]
Apart from the SaaS option, it's possible to download and install the software yourself. Maybe we could add it to the [GTFS Data Collection and Maintenance Tools](https://github.com/MobilityData/awesome-transit?tab=readme-ov-file#gtfs-data-collection-and-maintenance-tools) section but also keep the old converter as a reference.

**Comment by albanpeignier** [comment]
Hello, I'm a member of the enRoute team. 

Indeed, we're maintaining several open source transit tools. Chouette or Ara are now very large (and open source) applications. But we're providing many libraries (especially in ruby) to manage GTFS, GTFS-RT, NeTEx or SIRI contents. 

All projects are available on Bitbucket: https://bitbucket.org/enroute-mobi/ (some of them are replicated on https://github.com/enroute-mobi/).

**Comment by 1Maxnet1** [comment]
Thanks for the comments. As my original aim was only to update the broken link to a working one, I did so now to update this PR according to your proposals. Maybe @albanpeignier could properly add the available solutions enroute-mobi provides, as you are more qualified as a member of enroute-mobi, to describe your products.

**Pull request merged**
